modelPath = "/home/feet/Repos/Visibility-Networks/src/models/VisNet-3x200x200-3-Q.pt"

# [height, width]
imgDim = [200, 200]

# dimensions of FFT mask. [height, width]
maskDim = [22, 22]

batchSize = 16

epochs = 80

learningRate = 0.00001

dataPath = "/home/feet/datasets/

# 1 if doing regression
numClasses = 3

channels = 3

# names of classes if doing classifcation
classes = ["150m", "300m", "600m"]

# TRAIN, TEST, VALIDATE
mode = "VALIDATE"

# SSF, FCS, FROSI, ALL
dataset = "FCS"

# RMEP, VISNET, INTEGRATED
model = "VISNET"

# Use GPU
try_cuda = false

# Record the confi
recordCI = false