modelPath = "./example/trained-integrated-3x160x120.pt"

# [height, width]
imgDim = [120, 160]

# dimensions of FFT mask. [height, width]
maskDim = [22, 22]

batchSize = 16

epochs = 80

learningRate = 0.00001

dataPath = ""

# 1 if doing regression
numClasses = 1

channels = 3

# names of classes if doing classifcation
classes = ["150m", "300m", "600m"]

# TRAIN, TEST, VALIDATE
mode = "TRAIN"

# SSF, FCS, FROSI
dataset = "SSF"

# RMEP, VISNET, INTEGRATED
model = "INTEGRATED"

# Use GPU
try_cuda = false

# Record the confi
record_ci = false