modelPath = "./example/trained-rmep.pt"
imgDim = [120, 160]
maskDim = [22, 22]
batchSize = 16
epochs = 80
learningRate = 0.00001
dataPath = ""
numClasses = 1
channels = 3
#classes = ["50m", "100m", "150m", "200m", "250m", "300m", "400m"]
mode = "TRAIN"
dataset = "SSF"
model = "RMEP"
try_cuda = false
record_ci = false