modelPath = "/home/feet/Desktop/model/trained-rmep-3x160x120.pt"

# [height, width]
imgDim = [160, 120]

# dimensions of FFT mask. [height, width]
maskDim = [22, 22]

batchSize = 16

epochs = 80

learningRate = 0.00001

dataPath = "/home/feet/Downloads/leftImg8bit_trainval_foggyDBF/leftImg8bit_foggyDBF/"

# 1 if doing regression
numClasses = 1

channels = 3

# names of classes if doing classifcation
classes = ["150m", "300m", "600m"]

# TRAIN, TEST, VALIDATE
mode = "VALIDATE"

# SSF, FCS, FROSI
dataset = "SSF"

# RMEP, VISNET, INTEGRATED
model = "RMEP"

# Use GPU
try_cuda = false

# Record the confi
recordCI = false