modelPath = "/home/feet/Repos/Visibility-Networks/src/models/VisNet_Reduced-1x112x112-3.pt"
imgDim = [112, 112]
maskDim = [22, 22]
batchSize = 16
epochs = 80
learningRate = 0.00001
dataPath = "/home/feet/Downloads/FCS"
numClasses = 3
channels = 1
#classes = ["50m", "100m", "150m", "200m", "250m", "300m", "400m"]
classes = ["150m", "300m", "600m"]
mode = "TRAIN"
dataset = "FCS"
model = "VISNET"
try_cuda = false