modelPath = "/home/jmurr/Repos/Visibility-Networks/VisNet_Reduced-3x476x357-1.pt"

# [height, width]
imgDim = [357, 476]

# dimensions of FFT mask. [height, width]
maskDim = [71, 95]

batchSize = 6

epochs = 80

learningRate = 0.00005

dataPath = "/home/jmurr/Documents/LAWN/datasets/4-9-24-5-23-PM/images"

# 1 if doing regression
numClasses = 1

channels = 3

# names of classes if doing classifcation
classes = ["150m", "300m", "600m"]

# TRAIN, TEST, VALIDATE
mode = "TRAIN"

record_values = false

# SSF, FCS, FROSI, ALL
dataset = "WEBCAMS"

# RMEP, VISNET, INTEGRATED
model = "VISNET"

# Use GPU
try_cuda = false

# Record the confi
recordCI = false