modelPath = "/home/feet/Desktop/model-testing-with/RMEP/SSF/3x160x120/best-r2.pt"

# [height, width]
imgDim = [120, 160]

# dimensions of FFT mask. [height, width]
maskDim = [24, 32]

batchSize = 16

epochs = 80

learningRate = 0.00001

dataPath = "/home/feet/datasets/SSF"

# 1 if doing regression
numClasses = 1

channels = 3

# names of classes if doing classifcation
classes = ["150m", "300m", "600m"]

# TRAIN, TEST, VALIDATE
mode = "VALIDATE"

# SSF, FCS, FROSI, ALL
dataset = "SSF"

# RMEP, VISNET, INTEGRATED
model = "RMEP"

# Use GPU
try_cuda = false

# Record the confi
recordCI = false