modelPath = "/home/feet/Desktop/model-testing-with/Quantized/FCS/RMEP-FCS-3x256x256-3-Q.pt"

# [height, width]
imgDim = [256, 256]

# dimensions of FFT mask. [height, width]
maskDim = [24, 32]

batchSize = 16

epochs = 80

learningRate = 0.00001

dataPath = "/home/feet/datasets/FCS/leftImg8bit_foggyDBF/"

# 1 if doing regression
numClasses = 3

channels = 3

# names of classes if doing classifcation
classes = ["150m", "300m", "600m"]

# TRAIN, TEST, VALIDATE
mode = "VALIDATE"

# SSF, FCS, FROSI, ALL
dataset = "FCS"

# RMEP, VISNET, INTEGRATED
model = "RMEP"

# Use GPU
try_cuda = false

# Record the confi
recordCI = false