modelPath = "/home/jmurr/Repos/Visibility-Networks/RMEP-3x320x180-1.pt"

# [height, width]
imgDim = [180, 320]

# dimensions of FFT mask. [height, width]
maskDim = [24, 32]

batchSize = 16

epochs = 80

learningRate = 0.00001

dataPath = "/home/jmurr/Downloads/database/images"

# 1 if doing regression
numClasses = 1

channels = 3

# names of classes if doing classifcation
classes = ["150m", "300m", "600m"]

# TRAIN, TEST, VALIDATE
mode = "TRAIN"

record_values = false

# SSF, FCS, FROSI, ALL
dataset = "JACOBS"

# RMEP, VISNET, INTEGRATED
model = "RMEP"

# Use GPU
try_cuda = false

# Record the confi
recordCI = false